[wip] have a different error from blakejs
    jr: c_a2w_handler: error from controller Error: blakejs.blake2b is not a function content.ts:70:16
        onErrorCase content.ts:70
        (Async: promise callback)
        c_a2w_handler content.ts:83
        (Async: EventListener.handleEvent)
        c_main content.ts:100
        <anonymous> content.ts:106

tried using browserify on blake

think i need to inject it in the namespace like nacl

so progress